import java.util.List;

/**
* This verification object is generated by the lookup algorithm each time
* it visits a block of the chain.
*
* @author Matteo Loporchio, 491283
*/
public class VBlock implements VObject {
  /**
  * This is the verification object generated by the query algorithm
  * when traversing the MR-tree index for the block.
  */
  public final VObject block;

  /**
  * This is skip list entry that has been selected by the lookup algorithm.
  */
  public final SkipListEntry entry;

  /**
  * This is the list of the hash values of the skip list entries that have
  * been discarded.
  */
  public final List<byte[]> entryHashes;

  /**
  * This is the default constructor for the <code>VBlock</code> class.
  * @param block the verification object for the records in the block
  * @param entry the selected entry
  * @param entryHashes the list of hash values of the discarded entries
  */
  public VBlock(VObject block, SkipListEntry entry, List<byte[]> entryHashes) {
    this.block = block;
    this.entry = entry;
    this.entryHashes = entryHashes;
  }

}
